### ISSUE TITLE
With multiple targets, later targets will act on outputs of previous ones

### ISSUE THREAD

**Issue by n-ihlo** [spang-lab/urnc#41]
When specifying multiple targets, for example
```yaml
convert:
  targets:
    - type: student
      path: "{nb.abspath}"
    - type: solution
      path: "{nb.absdirpath}_solutions/{nb.name}"
```
the later targets (here the one with type solution) will not act on the original files, but on the converted files from the first target. In this case, this will lead to solution files with no solutions.
