### ISSUE TITLE
Feature: create solutions from notebooks

### ISSUE THREAD

**Issue by toscm** [spang-lab/urnc#5]
URNC should not only create student notebooks **without** solutions, but also student notebooks **with** solutions for every pattern listed in `config.yml/convert.solutions` [1]. For the initial version of this feature it's sufficient to just copy every specified notebook and rename it from `(.*)\.ipynb` to `$1_solution.ipynb`. Also, every solution should be ignored by default. This can be achieved by adding `*solution.ipynb` to `git.excludes` in `config.yml`. Inverted includes can then be used to selectively readd the solution files, e.g. using:

```yml
# config.yml
convert:
    solutions:
        assignments/*
git:
     excludes:
        *solution.ipynb
        01_whats_a_computer.ipynb
        02_file_systems.ipynb
        {pattern: "03_shell_solution.ipynb", after: "2023-10-31"}

```

[1]: Whoever implements this feature can also decide to use another config name.
